apiVersion: v1
kind: Service
metadata:
  name: flask-hello-world
  namespace: flask-hello-world
spec:
  type: LoadBalancer
  selector:
    app: flask-hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080

